" --- Plugins ---
" Plugin Manager: vim-plug (https://github.com/junegunn/vim-plug)
" Installation: https://github.com/junegunn/vim-plug?tab=readme-ov-file#installation

call plug#begin()
Plug 'morhetz/gruvbox'                   " https://github.com/morhetz/gruvbox
Plug 'itchyny/lightline.vim'             " https://github.com/itchyny/lightline.vim
Plug 'mengelbrecht/lightline-bufferline' " https://github.com/mengelbrecht/lightline-bufferline
Plug 'junegunn/fzf'                      " https://github.com/junegunn/fzf
Plug 'junegunn/fzf.vim'                  " https://github.com/junegunn/fzf.vim
" Plug 'yegappan/lsp'                    " https://github.com/yegappan/lsp
Plug 'airblade/vim-gitgutter'            " https://github.com/airblade/vim-gitgutter
Plug 'Yggdroot/indentLine'               " https://github.com/Yggdroot/indentLine
Plug 'tpope/vim-fugitive'                " https://github.com/tpope/vim-fugitive
Plug 'tpope/vim-commentary'              " https://github.com/tpope/vim-commentary
Plug 'prabirshrestha/vim-lsp'            " https://github.com/prabirshrestha/vim-lsp
Plug 'mattn/vim-lsp-settings'            " https://github.com/mattn/vim-lsp-settings
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
call plug#end()


" --- Source ---
source ~/.vim/options.vim     " Basic options
source ~/.vim/keybinds.vim    " Keybind
source ~/.vim/terminal.vim    " my terminal vimscript
source ~/.vim/plugin-lightline.vim
source ~/.vim/plugin-fzf.vim
source ~/.vim/plugin-lsp.vim
source ~/.vim/plugin-indentLine.vim
" source ~/.vim/plugin-vim-commentary.vim
" source ~/.vim/notice.vim


