set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g default-shell "/bin/zsh"

set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

set -g status-left-length 31
set -g status-left "#[bg=#{?client_prefix,#ff7575,#01815A}] session[#S] "
set -g status-style "bg=#394253"
set -g status-justify centre

set -g window-status-format "#I:#W"
set -g window-status-current-format "#[fg=#88C0D0]  #I:#W"

set -g status-right "--- this is TMUX --- "

unbind %
bind | split-window -h

unbind '"'
bind '-' split-window -v

unbind r
bind r source-file ~/.tmux.conf

bind h resize-pane -L 5
bind j resize-pane -D 5
bind k resize-pane -U 5
bind l resize-pane -R 5
bind -r m resize-pane -Z

setw -g mode-keys vi
